# @package _group_
nfolds: 7
nseed : 1
epochs: 25
lr: 1e-3
weight_decay: 1e-5
early_stopping_steps: 10
early_stop: false

hidden_size: 1500

dropout_model: 0.25

# PCA
n_comp_genes: 463
n_comp_cells: 60

# FS
variance_threshold_for_fs: 0.9

# Version
v: 0
# Our Patches
patch1: 0
train_models: 0