defaults:
  - model: train
  - pl: gpu100
  - datamodule: gpu
  - quantile_transformer: normal
#  - hydra/sweeper: ax
hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}