defaults:
  - mode: train
  - model1: model1
  - pl: gpu100
  - datamodule: gpu
  - quantile_transformer: normal
  - scheduler: oneCycleLR
  - logger: tensorboardlogger
  - earlystopping: 10
  - modelcheckpoint: top1
  - pca: pca_base
  - variance_threshold: variancethreshold_base
#  - hydra/sweeper: ax
hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}